# -*- coding: utf-8 -*-
"""ProyectoTestA/B

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q_6m88c1abHBbGHwePjkZxPSV5yuMKu2

## 1.- Introducción

# Sales Analysis Project — From Data Cleaning to A/B Testing

Este proyecto cubre el flujo completo de análisis de datos:

1. Carga del dataset original
2. Limpieza y preparación de datos
3. Generación de dataset limpio
4. Análisis A/B sobre descuentos
5. Preparación de datos para Power BI

El objetivo es transformar datos crudos en insights accionables.

##  Carga del dataset
Se carga el dataset original de ventas (Superstore), el cual contiene información de órdenes, clientes, productos y métricas de negocio.

Este dataset requiere limpieza antes de ser utilizado para análisis.
"""

import pandas as pd

df = pd.read_csv("/content/Sample - Superstore.csv", encoding='latin1')

df.head()

"""##  Exploración inicial

Se analiza la estructura del dataset para identificar:

- Tipos de datos
- Valores nulos
- Columnas inconsistentes
- Problemas de formato

Esto permite definir la estrategia de limpieza.
"""

df.info()
df.describe()

"""##  Limpieza de nombres de columnas

Se estandarizan los nombres de columnas:
- Se reemplazan puntos por guiones bajos
- Se eliminan espacios innecesarios
"""

df.columns = df.columns.str.replace('.', '_')
df.columns = df.columns.str.strip()

df.columns

"""##  Eliminación de columnas irrelevantes

Se eliminan columnas que no aportan valor al análisis o pueden generar ruido.
"""

df = df.drop(columns=['记录数'], errors='ignore')
df = df.drop(columns=['Row_ID','Year','Market2','weeknum'], errors='ignore')

"""##  Conversión de tipos de datos

Se convierten las columnas a sus tipos adecuados:
- Fechas → datetime
- Valores numéricos → float / int
"""

# fechas
df['Order Date'] = pd.to_datetime(df['Order Date'], errors='coerce')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], errors='coerce')

# numéricos
df['Sales'] = pd.to_numeric(df['Sales'], errors='coerce')
df['Profit'] = pd.to_numeric(df['Profit'], errors='coerce')
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')
df['Discount'] = pd.to_numeric(df['Discount'], errors='coerce')

"""##  Manejo de valores nulos

Se identifican y eliminan registros con valores faltantes para garantizar integridad de datos.
"""

df.isnull().sum()

df = df.dropna()

"""##  Validación final

Se verifica que el dataset esté limpio y correctamente estructurado.
"""

df.info()
df.head()

"""##  Exportación del dataset limpio

Generación del dataset limpio

Una vez procesados los datos, se genera un nuevo dataset listo para análisis.

Este dataset será utilizado para:
- Análisis estadístico
- Visualización en Power BI
"""

df.to_csv("superstore_clean_final.csv", index=False)

from google.colab import files
files.download("superstore_clean_final.csv")

"""## Diseño del experimento A/B

Se plantea un experimento para evaluar el impacto del descuento en el profit.

### Hipótesis:

- H0: El descuento no afecta el profit
- H1: El descuento sí afecta el profit

Se crean dos grupos:

- Grupo A (Control): Descuento bajo (≤ 10%)
- Grupo B (Tratamiento): Descuento alto (> 10%)
"""

df['Group'] = df['Discount'].apply(lambda x: 'A' if x <= 0.1 else 'B')

df[['Discount','Group']].head()

"""# Análisis descrptivo"""

ab_summary = df.groupby('Group').agg({
    'Sales':'mean',
    'Profit':'mean',
    'Quantity':'mean'
})

ab_summary

from scipy import stats

group_A = df[df['Group']=='A']['Profit']
group_B = df[df['Group']=='B']['Profit']

t_stat, p_value = stats.ttest_ind(group_A, group_B)

print("T-stat:", t_stat)
print("P-value:", p_value)

import matplotlib.pyplot as plt

df.boxplot(column='Profit', by='Group')
plt.title("Profit Distribution by A/B Group")
plt.suptitle("")
plt.show()

"""##  Interpretación del A/B Testing

El análisis muestra diferencias en el profit entre los grupos A y B.

- Si el p-value < 0.05:
  Existe evidencia estadística de que el descuento impacta el profit.

- Si el p-value ≥ 0.05:
  No hay evidencia suficiente para concluir que el descuento tenga efecto.

Este análisis permite evaluar estrategias de pricing basadas en datos.
"""

